apiVersion: v1
name: kibana
description: Kibana chart that runs on kubernetes
version: 1.0.14
keywords:
  - kibana
  - kubernetes
home: https://github.com/stakater-charts/kibana
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io