kubernetes:
  host: https://kubernetes.default

elasticSearch:
  host: elasticsearch
  port: 9200

kibana:
  namespace: default
  image:
    name: stakater/kibana
    tag: 6.1.0
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress