kubernetes:
  host: https://kubernetes.default

elasticSearch:
  host: http://elasticsearch.tools
  port: 9200

kibana:
  namespace: default
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 4.5
  image:
    name: stakater/kibana
    tag: 4.5
    pullPolicy: IfNotPresent
  configImage:
    name: stakater/kibana-config
    tag: 4.5
    pullPolicy: IfNotPresent
  service:
    annotations:
      config.xposer.stakater.com/IngressURLPath: "/"
      config.xposer.stakater.com/Domain: stackator.com
      config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
      config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Namespace}}.{{.Domain}}'
      config.xposer.stakater.com/TLS: "true"
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: internal-ingress
        ingress.kubernetes.io/force-ssl-redirect: true
        ingress.kubernetes.io/rewrite-target: /
        certmanager.k8s.io/cluster-issuer: letsencrypt-production
 # Add these annotations under xposer.stakater.com/annotations
 # forecastle.stakater.com/expose: true
 # forecastle.stakater.com/icon: https://cdn-images-1.medium.com/max/521/0*D__TQ7qMdoq3Y7kP.png
  probes:
    liveness:
      initialDelaySeconds: 60
    readiness:
      initialDelaySeconds: 60
  config:
    # serverBasePath: /kibana
    defaultAppId: "discover/All-logs"
  proxy:
    enabled: true
    image:
      name: quay.io/gambol99/keycloak-proxy
      tag: v2.1.1
      pullPolicy: IfNotPresent
    config:
      filePath: /etc/config/config.yml
      upstreamUrl: http://127.0.0.1:5601
      redirectionUrl: /kibana
      upstreamResponseHeaderTimeout: 30s
      upstreamTimeout: 30s
      upstreamKeepAliveTimeout: 30s
      serverReadTimeout: 30s
      serverWriteTimeout: 30s
