---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
    annotations:
      configmap.fabric8.io/update-on-change: "keycloak-proxy"
    name: kibana
  spec:
    replicas: 1
    selector:
      matchLabels:
{{ include "labels.selector" . | indent 8 }}
    template:
      metadata:
        labels:
{{ include "labels.selector" . | indent 10 }}
      spec:
        containers:
        - env:
          - name: ELASTICSEARCH_URL
            value: {{ .Values.elasticSearch.host }}:{{ .Values.elasticSearch.port }}
          - name: KUBERNETES_MASTER
            value: {{ .Values.kubernetes.host }}
          - name: SERVER_BASEPATH
            value: {{ .Values.kibana.config.serverBasePath }}
          # For EK 6+ setup
          # - name: ELASTICSEARCH_HOST
          #   value: elasticsearch.tools
          # - name: ELASTICSEARCH_PORT
          #   value: '9200'
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # image: stakater/kibana:6.1.0
          image: "{{ .Values.kibana.image.name }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.kibana.probes.liveness.initialDelaySeconds }}
            tcpSocket:
              port: 5601
          name: {{ template "name" . }}
          readinessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: {{ .Values.kibana.probes.readiness.initialDelaySeconds }}
          securityContext:
            privileged: false
        - env:
          - name: ELASTICSEARCH_URL
            value: {{ .Values.elasticSearch.host }}:{{ .Values.elasticSearch.port }}
          - name: KUBERNETES_MASTER
            value: {{ .Values.kubernetes.host }}
          image: "{{ .Values.kibana.configImage.name }}:{{ .Values.kibana.configImage.tag }}"
          imagePullPolicy: {{ .Values.kibana.configImage.pullPolicy }}
          name: logstash-template
        - name: proxy
          image: "{{ .Values.kibana.proxy.image.name }}:{{ .Values.kibana.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.proxy.image.pullPolicy }}
          args:
          - --config={{ .Values.kibana.proxy.config.filePath }}
          - --upstream-url={{ .Values.kibana.proxy.config.upstreamUrl }}
          - --redirection-url={{ .Values.kibana.proxy.config.redirectionUrl }}
          - --upstream-response-header-timeout={{ .Values.kibana.proxy.config.upstreamResponseHeaderTimeout }}
          - --upstream-timeout={{ .Values.kibana.proxy.config.upstreamTimeout }}
          - --upstream-keepalive-timeout={{ .Values.kibana.proxy.config.upstreamKeepAliveTimeout }}
          - --server-read-timeout={{ .Values.kibana.proxy.config.serverReadTimeout }}
          - --server-write-timeout={{ .Values.kibana.proxy.config.serverWriteTimeout }}
          volumeMounts:
          - name: keycloak-proxy-config
            mountPath: /etc/config
        volumes:
          - name: keycloak-proxy-config
            configMap:
              name: keycloak-proxy
# For EK 6+ setup
# Container for submitting index-pattern, visualizations and dashboard to kibana
# WIP
#        - env:
#          - name: ELASTICSEARCH_URL
#            value: http://elasticsearch.tools:9200
#          - name: KUBERNETES_MASTER
#            value: https://kubernetes.default
#          image: stakater/kibana-k8s-objects:develop
#          name: kibana-objects
