---
apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg
      fabric8.io/git-branch: release-v2.2.311
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.311
    labels:
      provider: fabric8
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: 2.2.311
      group: io.fabric8.devops.apps
    name: kibana
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ template "fullname" . }}
        provider: fabric8
        group: io.fabric8.devops.apps
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/kibana/src/main/fabric8/icon.svg
          fabric8.io/git-branch: release-v2.2.311
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=kibana&var-version=2.2.311
        labels:
          provider: fabric8
          app: {{ template "fullname" . }}
          chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
          version: 2.2.311
          group: io.fabric8.devops.apps
      spec:
        containers:
        - env:
          - name: KUBERNETES_MASTER
            value: {{ .Values.kubernetes.host }}
          - name: ELASTICSEARCH_HOST
            value: {{ .Values.elasticSearch.host }}
          - name: ELASTICSEARCH_PORT
            value: {{.Values .elasticSearch.port | quote }}
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: "{{ .Values.kibana.image.name }}:{{ .Values.kibana.image.tag }}"
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: 5601
          name: kibana
          readinessProbe:
            httpGet:
              path: /
              port: 5601
            initialDelaySeconds: 5
          securityContext:
            privileged: false
# Container for submitting index-pattern, visualizations and dashboard to kibana
# WIP
#        - env:
#          - name: ELASTICSEARCH_URL
#            value: http://elasticsearch:9200
#          - name: KUBERNETES_MASTER
#            value: https://kubernetes.default
#          image: stakater/kibana-k8s-objects:develop
#          name: kibana-objects