---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
{{- if .Values.kibana.service.annotations }}
    annotations:
{{ toYaml .Values.kibana.service.annotations | indent 6 }}
{{- end }}
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
      expose: "{{ .Values.kibana.service.expose }}"
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
    {{- if .Values.kibana.proxy.enabled }}
      targetPort: 80
    {{- else }}
      targetPort: 5601
    {{- end }}
    selector:
{{ include "labels.selector" . | indent 6 }}
