---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/ingress.annotations: |-
        ingress.kubernetes.io/force-ssl-redirect: false
        kubernetes.io/ingress.class: {{ .Values.kibana.service.ingressClass }}
    labels:
      provider: fabric8
      expose: "true"
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name | quote }}
      heritage: {{ .Release.Service | quote }}
      version: 2.2.311
      group: io.fabric8.devops.apps
    name: kibana
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5601
    selector:
      app: {{ template "fullname" . }}
      provider: fabric8
      group: io.fabric8.devops.apps
