---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/ingress.path: /{{ template "name" . }}
      fabric8.io/ingress.annotations: |-
        ingress.kubernetes.io/rewrite-target: /
        ingress.kubernetes.io/force-ssl-redirect: {{ .Values.kibana.service.forceSslRedirect }}
        kubernetes.io/ingress.class: {{ .Values.kibana.service.ingressClass }}
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
      expose: "{{ .Values.kibana.service.expose }}"
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
    {{- if .Values.kibana.proxy.enabled }}
      targetPort: 80
    {{- else }}
      targetPort: 5601
    {{- end }}
    selector:
{{ include "labels.selector" . | indent 6 }}
